# System-Wide Entity Health Monitoring Package
# Scans ALL entities across monitored domains for unavailable/stale states
# Location: packages/system_entity_health.v1.0.yaml
# Version: 1.1
# Created: 2026-01-25
# Updated: 2026-01-25 - Lowered thresholds, added auto-healing triggers

# ============================================================
# TEMPLATE SENSORS
# ============================================================

template:
  - sensor:
      # Count of all unavailable entities across monitored domains
      - name: "System Unavailable Entities"
        unique_id: system_unavailable_entities
        icon: mdi:alert-circle
        state: >
          {% set domains = ['sensor', 'binary_sensor', 'switch', 'light',
                            'climate', 'vacuum', 'lock', 'fan', 'cover',
                            'media_player', 'camera'] %}
          {{ states | selectattr('domain', 'in', domains)
                    | selectattr('state', 'in', ['unavailable', 'unknown'])
                    | list | count }}
        attributes:
          entities: >
            {% set domains = ['sensor', 'binary_sensor', 'switch', 'light',
                              'climate', 'vacuum', 'lock', 'fan', 'cover',
                              'media_player', 'camera'] %}
            {{ states | selectattr('domain', 'in', domains)
                      | selectattr('state', 'in', ['unavailable', 'unknown'])
                      | map(attribute='entity_id') | list }}
          by_domain: >
            {% set domains = ['sensor', 'binary_sensor', 'switch', 'light',
                              'climate', 'vacuum', 'lock', 'fan', 'cover',
                              'media_player', 'camera'] %}
            {% set ns = namespace(result={}) %}
            {% for domain in domains %}
              {% set count = states | selectattr('domain', 'eq', domain)
                                    | selectattr('state', 'in', ['unavailable', 'unknown'])
                                    | list | count %}
              {% if count > 0 %}
                {% set ns.result = dict(ns.result, **{domain: count}) %}
              {% endif %}
            {% endfor %}
            {{ ns.result }}
          last_scan: "{{ now().isoformat() }}"

      # Count of stale entities (no update in threshold hours)
      - name: "System Stale Entities"
        unique_id: system_stale_entities
        icon: mdi:clock-alert
        state: >
          {% set threshold_hours = 24 %}
          {% set domains = ['sensor', 'binary_sensor'] %}
          {% set threshold_ts = now() - timedelta(hours=threshold_hours) %}
          {{ states | selectattr('domain', 'in', domains)
                    | rejectattr('state', 'in', ['unavailable', 'unknown'])
                    | selectattr('last_changed', 'lt', threshold_ts)
                    | list | count }}
        attributes:
          entities: >
            {% set threshold_hours = 24 %}
            {% set domains = ['sensor', 'binary_sensor'] %}
            {% set threshold_ts = now() - timedelta(hours=threshold_hours) %}
            {{ states | selectattr('domain', 'in', domains)
                      | rejectattr('state', 'in', ['unavailable', 'unknown'])
                      | selectattr('last_changed', 'lt', threshold_ts)
                      | map(attribute='entity_id') | list }}
          threshold_hours: 24
          last_scan: "{{ now().isoformat() }}"

      # Entity health summary for dashboard
      - name: "Entity Health Summary"
        unique_id: entity_health_summary
        icon: mdi:heart-pulse
        state: >
          {% set unavailable = states('sensor.system_unavailable_entities') | int(0) %}
          {% set stale = states('sensor.system_stale_entities') | int(0) %}
          {% if unavailable > 10 %}
            critical
          {% elif unavailable > 5 %}
            warning
          {% elif unavailable > 0 or stale > 0 %}
            degraded
          {% else %}
            healthy
          {% endif %}
        attributes:
          unavailable_count: "{{ states('sensor.system_unavailable_entities') | int(0) }}"
          stale_count: "{{ states('sensor.system_stale_entities') | int(0) }}"

# ============================================================
# AUTOMATIONS
# ============================================================

automation:
  # Alert when ANY entity becomes unavailable
  - alias: "System Health: Unavailable Entity Alert"
    id: system_health_unavailable_entity_alert
    description: >
      Notify when any entity becomes unavailable for 5+ minutes.
      Immediate awareness of integration issues.
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.system_unavailable_entities
        above: 0
        for:
          minutes: 5
    action:
      - service: notify.mobile_app_andre_iphone
        data:
          title: "Entity Health Warning"
          message: >
            {{ states('sensor.system_unavailable_entities') }} entities unavailable.
            {% set by_domain = state_attr('sensor.system_unavailable_entities', 'by_domain') %}
            {% if by_domain %}Top domains: {{ by_domain }}{% endif %}
          data:
            push:
              interruption-level: time-sensitive
            url: /lovelace/system-health
      - service: logbook.log
        data:
          name: "WATCHDOG_ENTITY_HEALTH"
          message: >
            High unavailable count: {{ states('sensor.system_unavailable_entities') }} entities

  # Alert when entity health returns to normal (all entities available)
  - alias: "System Health: Entity Health Recovered"
    id: system_health_entity_health_recovered
    description: "Notify when all entities are available again"
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.system_unavailable_entities
        below: 1
    action:
      - service: notify.mobile_app_andre_iphone
        data:
          title: "Entity Health Recovered"
          message: "All monitored entities are now available"

  # Daily entity health summary (only if issues exist)
  - alias: "System Health: Daily Entity Summary"
    id: system_health_daily_entity_summary
    description: "Send daily summary of entity health at 8 AM if issues exist"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition:
      - condition: template
        value_template: >
          {{ states('sensor.system_unavailable_entities') | int(0) > 0 or
             states('sensor.system_stale_entities') | int(0) > 0 }}
    action:
      - service: notify.mobile_app_andre_iphone
        data:
          title: "Daily Entity Health Report"
          message: >
            {% set unavailable = states('sensor.system_unavailable_entities') | int(0) %}
            {% set stale = states('sensor.system_stale_entities') | int(0) %}
            {% if unavailable > 0 %}{{ unavailable }} unavailable entities. {% endif %}
            {% if stale > 0 %}{{ stale }} stale entities (>24h).{% endif %}
          data:
            url: /lovelace/system-health

  # ============================================================
  # AUTO-HEALING TRIGGERS
  # Link entity health monitoring to existing self-healing automations
  # ============================================================

  # Auto-trigger Jose recovery when battery sensor unavailable
  - alias: "System Health: Auto-Trigger Jose Recovery"
    id: system_health_auto_trigger_jose_recovery
    description: >
      Triggers Jose self-healing when sensor.jose_battery is unavailable for 10 min.
      Faster than the 2-hour watchdog threshold for quicker recovery.
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.jose_battery
        to:
          - "unavailable"
          - "unknown"
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.ecovacs_recovery_enabled
        state: "on"
    action:
      - service: logbook.log
        data:
          name: "WATCHDOG_AUTO_TRIGGER"
          message: "Jose unavailable for 10 min - triggering recovery"
      - service: automation.trigger
        target:
          entity_id: automation.jose_connection_watchdog

  # Auto-trigger EV9 recovery when battery sensor unavailable
  - alias: "System Health: Auto-Trigger EV9 Recovery"
    id: system_health_auto_trigger_ev9_recovery
    description: >
      Triggers EV9 self-healing when sensor.ev9_ev_battery_level is unavailable for 10 min.
      Faster than the 2-hour watchdog threshold for quicker recovery.
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ev9_ev_battery_level
        to:
          - "unavailable"
          - "unknown"
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.ev9_connection_watchdog_enabled
        state: "on"
    action:
      - service: logbook.log
        data:
          name: "WATCHDOG_AUTO_TRIGGER"
          message: "EV9 unavailable for 10 min - triggering recovery"
      - service: automation.trigger
        target:
          entity_id: automation.ev9_connection_watchdog
